design auth screens
Mubashar-Stack/NurseAIApp pull request #1
Opened 2024-09-27 06:30 UTC by salehanoor644

2024-09-27 07:07 UTC, Mubashar-Stack requested changes
I've reviewed your code, so please check the comments and address the issues. Also, ensure the screens follow the Figma flow — for example, the initial screen is missing. I'll run the code locally this evening and let you know if any further improvements are needed

2024-09-27 07:07 UTC, Mubashar-Stack commented on src/components/Header/Header.tsx
> +import { Text } from '../../../blueprints/Text/Text';
Don't use this dot dot while accessing the blueprints instead you can use this `@app/blueprints`

2024-09-27 07:07 UTC, Mubashar-Stack commented on src/components/Header/Header.tsx
> +      {title == 'Sign Up' || title == 'Log In' ? (
Refactored Header component for improved condition handling and TypeScript support. Example: replaced inline condition with `isAuthScreen` variable.
`const isAuthScreen = ['Sign Up', 'Log In'].includes(title);`

2024-09-27 07:07 UTC, Mubashar-Stack commented on src/constants/MainStyles.tsx
> +  fontFamily: 'Montserrat-Medium',
Use this font (Roboto)  as per figma

2024-09-27 07:07 UTC, Mubashar-Stack commented on src/navigation/AppNavigation.tsx
> +          <Stack.Screen name={Screen.NEWS_DETAIL} component={NewsDetailScreen} />
Remove extra screens from code and navigation stack as well

2024-09-27 07:07 UTC, Mubashar-Stack commented on src/screens/Login/Login.style.ts
> +//       flex: 2,
Please avoid commenting out code like this. If it's not needed, remove it entirely.

2024-09-27 07:07 UTC, Mubashar-Stack commented on src/screens/Login/LoginScreen.tsx
> +import { Screen } from '../../navigation/appNavigation.type'
Here is the alias list. Please use these, with the default being src. Start with `@src` and follow the structure onward
```
alias: {
  '@app/blueprints': './blueprints',
  '@src/assets': './src/assets',
  '@src/components': './src/components',
  '@src/constants': './src/constants',
  '@src/context': './src/context',
  '@src/hooks': './src/hooks',
  '@src/i18n': './src/i18n',
  '@src/screens': './src/screens',
  '@src/services': './src/services',
  '@src/store': './src/store',
  '@src/utils': './src/utils',
}
```

2024-09-27 08:59 UTC, mirajkhandev commented on src/components/Header/Header.tsx
> +import { Text } from '../../../blueprints/Text/Text';
okay

2024-09-28 07:26 UTC, mirajkhandev commented on src/components/Header/Header.tsx
> +      {title == 'Sign Up' || title == 'Log In' ? (
Done

2024-09-28 10:24 UTC, Mubashar-Stack approved these changes

2024-09-28 10:24 UTC, merged